t = input('Digite algo: ')
print('Tipo primitivo: {}'.format(type(t)))
print('É alpha? ', t.isalpha())
print('É numeric? ', t.isnumeric())
print('É dígito? ', t.isdigit())
print('É decimal', t.isdecimal())
print('É alphanum? ', t.isalnum())
print('Está em letras maiúsculas? ', t.isupper())
print('Está em letras minúsculas? {}'.format(t.islower()))
print('É um espaço? ', t.isspace())
