n1 = int(input('Digite o 1° número: '))
n2 = int(input('Digite o 2° número: '))
n3 = int(input('Digite o 3° número: '))
print('O menor valor é ', min(n1, n2, n3))
print('O maior valor é ', max(n1, n2, n3))
